const projects = [
  {
    id: 1,
    img: "/movie pc.png",
    desc: "i built this crypto website using Next.js and API, it is a dynamic platform that provides real-time information on cryptocurrencies. It offers a clean interface with details about various cryptocurrencies, interactive charts, personalized alerts, and a portfolio management feature. Users can explore, analyze, and manage cryptocurrencies effectively on the site.",
    title: " Crypto-X",
    technologies: [
      "/images/tailwind.png",
      "/images/firebase.png",
      "/images/next.jpg",
      "/images/typescript.png",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv-4udUlXO3_X0cCm6S0cnqt61-D9mGemoUw&usqp=CAU",
    ],
    link: "https://crypto-x-murex.vercel.app/",
  },
  {
    id: 2,
    img: "/images/facebook.png",
    desc: "The Facebook clone I built using Next.js is a social media platform resembling Facebook's design and functionality. It allows users to connect with friends, post updates, photos, and videos, receive real-time notifications, and control privacy settings. The clone provides a familiar social media experience with features like events, groups, and marketplace.",
    title: " Facebook-2.0 ",
    technologies: [
      "/images/tailwind.png",
      "/images/next.jpg",
      "/images/firebase.png",
    ],
    link: "https://facebook-2-0-sandy.vercel.app/",
  },
  {
    id: 3,
    img: "/images/instagram.png",
    desc: "The Instagram clone I built using Next.js is a social media platform resembling Instagram's design and functionality. It allows users to connect with friends, post updates, photos, and videos, receive real-time notifications, and control privacy settings. The clone provides a familiar social media experience with features like events, groups, and marketplace.",
    title: " Instagram-2.0 ",
    technologies: [
      "/images/tailwind.png",
      "/images/next.jpg",
      "/images/firebase.png",
    ],
    link: "https://instagram-2-0-seven.vercel.app",
  },
  {
    id: 4,
    img: "/images/arone.png",
    desc: "I assisted in adding new functionalities to a site, enhancing its capabilities. These additions make the site more interactive, engaging, and user-friendly.",
    title: "  Arone Energy",
    technologies: [
      "/images/tailwind.png",
      "/images/javascript.png",
      "/images/html.png",
      "/images/css.png",
      "/images/swiper.png",
    ],
    link: "https://www.aroneenergy.com/",
  },
  {
    id: 5,
    img: "/images/google.png",
    desc: "The Google Site clone I built using Google API replicates the features and design of Google Sites. It integrates with Google services  like the search functionality. Users can leverage Google services seamlessly.",
    title: " Google Clone",
    technologies: [
      "/images/tailwind.png",
      "/images/next.jpg",
      "/images/javascript.png",
      "/images/firebase.png",
    ],
    link: "https://facebook-2-0-sandy.vercel.app/",
  },
  {
    id: 6,
    img: "/images/hulu.png",
    desc: "The dynamic page I developed, similar to Hulu, utilizes an API to provide a wide range of movies and TV shows. Users can browse, search, and personalize their viewing experience.",
    title: " Hulu ",
    technologies: [
      "/images/tailwind.png",
      "/images/next.jpg",
      "/images/javascript.png",
    ],
    link: "https://hulu-peach-three.vercel.app/",
  },
  {
    id: 7,
    img: "/images/movies.png",
    desc: "The streaming app I developed allows users to stream movies using an API. It provides a wide collection of movies, real-time data, seamless streaming, and interactive features like personalized recommendations and user reviews.",
    title: " MovieNow ",
    technologies: [
      "/images/tailwind.png",
      "/images/next.jpg",
      "/images/javascript.png",
    ],
    link: "https://movie-app-seven-zeta.vercel.app/login",
  },
  {
    id: 8,
    img: "/images/weather (2).png",
    desc: "The weather app I developed uses an API to provide real-time weather information. Users can view current conditions, hourly and extended forecasts, and customize preferences. It offers a user-friendly interface with accurate and up-to-date weather data.",
    title: " StormWatch ",
    technologies: [
      "/images/tailwind.png",
      "/images/next.jpg",
      "/images/javascript.png",
    ],
    link: "https://weather-app-azure-two-50.vercel.app/",
  },
];
export default projects;
